Update _config.yml
blogbasti/klangturm pull request #8
Opened 2021-05-22 18:49 UTC by lushsounds

Adressangabe gekürzt

2021-05-23 18:25 UTC, blogbasti requested changes
Die Seite "About" würde ich im Titel nicht einfach auf "info" ändern. "Über" oder "About" sagt schon mehr aus, da defacto jede Seite "Info"rmationen enthalten. Zudem lässt sich der Name "About" gut in andere Sprachen zu übersetzen. Daher würde ich empfehlen, die Seite weiterhin mit "About" zu betiteln.

2021-05-23 18:27 UTC, lushsounds commented
ja o.k.
nur zur Erklärung: Das war mein Versuch, mit info als international verständliches Wort alle Sprachen auf dieser Seite zu vereinen.
Aber ich lasse Dich erstmal machen, wie besprochen.
Danke und liebe Grüße
b

2021-05-23 18:43 UTC, lushsounds commented
Sebastian, hatte jetzt nochmal eine Änderung vorgeschlagen, aber hier sehe ich, dass ein Check failed?

2021-05-23 18:43 UTC, closed without merging

2021-05-23 18:44 UTC, lushsounds commented
Muss ich eigentlich den Pull-Request immer schließen? Habe das jetzt mal getan zum Test. 
Bisher ging es aber auch ohne zu schließen.

2021-05-24 14:35 UTC, blogbasti commented
Normalerweise verknüpft man den pull request mit dem issue. Dieser wird damit beim merge automatisch geschlossen.